<%@ Page Title="" Language="VB" MasterPageFile="MasterPage.master" AutoEventWireup="false" CodeFile="CoreProducts.aspx.vb" Inherits="CoreProducts" %>


<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" Runat="Server">
    <div id="text" style="font-size:14px;">
    <div id="coreProd">
        <br />
        <br />
    <asp:Label ID="Label1" runat="server" Text="Choose a Category:"></asp:Label>
        <br />
    <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="True">
        <asp:ListItem Value="0">Select</asp:ListItem>
        <asp:ListItem Value="1">Headgear</asp:ListItem>
        <asp:ListItem Value="2">Aprons/Sleeves</asp:ListItem>
        <asp:ListItem Value="3">Coveralls</asp:ListItem>
        <asp:ListItem Value="4">Shoe Covers</asp:ListItem>
        <asp:ListItem Value="5">Lab Coats</asp:ListItem>
    </asp:DropDownList>
        <br />
        <br />
    <asp:Label ID="lblProd" runat="server" Text="Available Products:" Visible="False"></asp:Label>

        <div style="overflow:auto; height:320px; margin:auto; width:70%"; >
    <asp:GridView ID="GridView1"  runat="server" AutoGenerateSelectButton="True" DataKeyNames="Item_ID"></asp:GridView>
            <br />
           
    <asp:GridView ID="GridView2" runat="server" AutoGenerateDeleteButton="True"></asp:GridView>
            </div>
        <br />
        
    <asp:Label ID="lblTotal" runat="server" Text="Total"></asp:Label>

    <asp:Label ID="lblAmount" runat="server" Text="Amount"></asp:Label>

    <asp:Button ID="btnCheckout" runat="server" Text="Check Out" />
        </div>
        </div>
    </asp:Content>
